export const strings = {
  common: {
    status: 'Status',
    loading: 'Carregando...',
    notAvailable: '—',
    signOut: 'Sair da conta',
  },
  auth: {
    signInTitle: 'Entrar no Prudens Index',
    signInSubtitle: 'Escolha seu perfil e faça login com e-mail e senha.',
    profileGroupLabel: 'Tipo de acesso',
    profileAdmin: 'Administrador',
    profileClient: 'Cliente',
    mismatchUseAdmin:
      'Esta conta é de administrador. Selecione Administrador acima e entre novamente.',
    mismatchUseClient:
      'Esta conta é de cliente. Selecione Cliente acima e entre novamente.',
    pendingInviteHint:
      'Se você recebeu um convite por e-mail, abra o link do convite para ativar sua conta.',
    verifyTitle: 'Confirmar código',
    verifySubtitle: 'Digite o código enviado para o seu e-mail.',
    verifySpamHint: 'Se não receber, verifique a pasta de spam.',
    verifyCodeLabel: 'Código de verificação',
    verifySubmit: 'Confirmar',
    verifyResend: 'Reenviar código',
    verifyResendSuccess: 'Novo código enviado para o seu e-mail.',
    verifyUnsupportedFactor:
      'Verificação por e-mail não está disponível para esta conta. Entre em contato com o suporte.',
    verifySessionExpired: 'Sessão de login expirada. Entre novamente.',
    verifyBackToLogin: 'Voltar ao login',
    verifyInvalidCode: 'Código inválido ou expirado. Tente novamente.',
    signInIncomplete: 'Não foi possível concluir o login. Tente novamente.',
    inviteTitle: 'Criar sua senha',
    inviteSubtitle: 'Defina uma senha para ativar sua conta.',
    newPassword: 'Nova senha',
    confirmPassword: 'Confirmar senha',
    inviteSubmit: 'Ativar conta',
    inviteInvalid:
      'Link de convite inválido ou expirado. Solicite um novo convite ao administrador.',
    passwordMismatch: 'As senhas não coincidem.',
  },
  nav: {
    filters: 'Filtros',
    clearFilters: 'Limpar filtros',
    searchProduct: 'Buscar por nome ou EAN',
    statusFilter: 'Status do item',
    iddRange: 'Faixa de IDD',
    stockDaysRange: 'Dias de estoque',
    capitalRange: 'Capital imobilizado',
    collapseMenu: 'Recolher menu',
    expandMenu: 'Expandir menu',
  },
  admin: {
    companies: 'Empresas',
    newCompany: 'Nova empresa',
    newCompanyTitle: 'Nova empresa',
    newCompanyBreadcrumb: 'Nova empresa',
    companyName: 'Nome da empresa',
    companyCnpj: 'CNPJ',
    companyAddress: 'Endereço',
    companyNeighborhood: 'Bairro',
    companyCity: 'Cidade',
    companyState: 'UF',
    createCompany: 'Cadastrar empresa',
    creatingCompany: 'Cadastrando...',
    cnpjDuplicate: 'CNPJ já cadastrado',
    imports: 'Importações',
    uploadSpreadsheet: 'Importar planilha de estoque',
    noCompanies: 'Nenhuma empresa cadastrada.',
    loadingCompanies: 'Carregando empresas...',
    importHistory: 'Histórico de importações',
    importSpreadsheetForCompany: 'Importar planilha para esta empresa',
    noImportsForCompany: 'Nenhuma importação registrada para esta empresa.',
    backToCompanies: 'Voltar para empresas',
    activeDashboardSource: 'Fonte ativa do dashboard do cliente',
    activeJob: 'Job ativo',
    noActiveImport: 'Nenhuma importação ativa.',
    users: 'Usuários',
    usersTitle: 'Gestão de usuários',
    usersDescription:
      'Convide administradores e clientes, acompanhe convites pendentes e ajuste perfis de acesso.',
    userEmail: 'E-mail',
    userRole: 'Perfil',
    userCompany: 'Empresa',
    userStatus: 'Status',
    roleAdmin: 'Administrador',
    roleClient: 'Cliente',
    statusActive: 'Ativo',
    statusPending: 'Pendente de ativação',
    inviteUser: 'Enviar convite',
    invitingUser: 'Enviando convite...',
    editUser: 'Editar',
    saveUser: 'Salvar alterações',
    savingUser: 'Salvando...',
    cancelEdit: 'Cancelar',
    noUsers: 'Nenhum usuário cadastrado ainda. Envie o primeiro convite abaixo.',
    loadUsersError: 'Não foi possível carregar os usuários.',
    retryLoad: 'Tentar novamente',
    inviteSuccess: 'Convite enviado com sucesso.',
    updateSuccess: 'Usuário atualizado com sucesso.',
    emailReadonly: 'O e-mail não pode ser alterado após o convite.',
  },
  client: {
    unitPrice: 'Valor Unitário',
    unitPriceShort: 'V. unit.',
    projectedRevenue: 'Faturamento Projetado',
    projectedRevenueShort: 'Fat. projetado',
    tiedUpCapital: 'Capital Imobilizado',
    tiedUpCapitalShort: 'Cap. imobilizado',
    lostRevenue: 'Faturamento Perdido',
    lostRevenueShort: 'Fat. perdido',
    chartTitle: 'Gráfico de Produto por IDD',
    noChartData: 'Nenhum produto para exibir no gráfico.',
    productsPageInfo: 'de',
    productsLabel: 'produtos',
    currentPage: 'página atual',
    updatingProducts: 'Atualizando produtos...',
    noStockData:
      'Nenhum dado de estoque disponível ainda. Aguarde o administrador concluir uma importação para sua empresa.',
    exportSpreadsheet: 'Exportar planilha',
    exportDownloading: 'Baixando...',
    exportDisabledTooltip: 'Não há planilha ativa para exportar.',
  },
  errors: {
    uploadFailed: 'Falha no upload',
    invalidSpreadsheet:
      'Selecione uma planilha (.xlsx, .xls, .xlsm, .xlsb, .csv, .tsv ou .ods)',
    loadCompanies: 'Erro ao carregar empresas',
    validationErrorsTitle: 'Erros de validação da planilha',
    missingColumnsTitle: 'Colunas ausentes na planilha',
    missingColumnsHint:
      'A importação foi concluída com os dados disponíveis. Campos das colunas abaixo ficam vazios (—) no painel do cliente.',
    noValidationErrors: 'Nenhum erro de validação para este job.',
    spreadsheetOnly: 'Apenas arquivos de planilha são permitidos',
  },
  statusLabels: {
    queued: 'Na fila',
    processing: 'Processando',
    completed: 'Concluído',
    failed: 'Falhou',
  },
  itemStatus: {
    distribution: 'Redistribuição',
    adequate: 'Adequado',
    boost: 'Impulsionar',
  },
} as const;
