export const strings = {
  common: {
    status: 'Status',
    loading: 'Carregando...',
    notAvailable: '—',
    signOut: 'Sair da conta',
  },
  admin: {
    companies: 'Empresas',
    newCompany: 'Nova empresa',
    newCompanyTitle: 'Nova empresa',
    newCompanyBreadcrumb: 'Nova empresa',
    companyName: 'Nome da empresa',
    companyCnpj: 'CNPJ',
    companyAddress: 'Endereço',
    companyNeighborhood: 'Bairro',
    companyCity: 'Cidade',
    companyState: 'UF',
    createCompany: 'Cadastrar empresa',
    creatingCompany: 'Cadastrando...',
    cnpjDuplicate: 'CNPJ já cadastrado',
    imports: 'Importações',
    uploadSpreadsheet: 'Importar planilha de estoque',
    noCompanies: 'Nenhuma empresa cadastrada.',
    loadingCompanies: 'Carregando empresas...',
    importHistory: 'Histórico de importações',
    importSpreadsheetForCompany: 'Importar planilha para esta empresa',
    noImportsForCompany: 'Nenhuma importação registrada para esta empresa.',
    backToCompanies: 'Voltar para empresas',
    activeDashboardSource: 'Fonte ativa do dashboard do cliente',
    activeJob: 'Job ativo',
    noActiveImport: 'Nenhuma importação ativa.',
  },
  client: {
    unitPrice: 'Valor Unitário',
    unitPriceShort: 'V. unit.',
    projectedRevenue: 'Faturamento Projetado',
    projectedRevenueShort: 'Fat. projetado',
    tiedUpCapital: 'Capital Imobilizado',
    tiedUpCapitalShort: 'Cap. imobilizado',
    lostRevenue: 'Faturamento Perdido',
    lostRevenueShort: 'Fat. perdido',
    noChartData: 'Nenhum produto para exibir no gráfico.',
    productsPageInfo: 'de',
    productsLabel: 'produtos',
    currentPage: 'página atual',
    updatingProducts: 'Atualizando produtos...',
    noStockData:
      'Nenhum dado de estoque disponível ainda. Aguarde o administrador concluir uma importação para sua empresa.',
  },
  errors: {
    uploadFailed: 'Falha no upload',
    invalidSpreadsheet:
      'Selecione uma planilha (.xlsx, .xls, .xlsm, .xlsb, .csv, .tsv ou .ods)',
    loadCompanies: 'Erro ao carregar empresas',
    validationErrorsTitle: 'Erros de validação da planilha',
    missingColumnsTitle: 'Colunas ausentes na planilha',
    missingColumnsHint:
      'A importação foi concluída com os dados disponíveis. Campos das colunas abaixo ficam vazios (—) no painel do cliente.',
    noValidationErrors: 'Nenhum erro de validação para este job.',
    spreadsheetOnly: 'Apenas arquivos de planilha são permitidos',
  },
  statusLabels: {
    queued: 'Na fila',
    processing: 'Processando',
    completed: 'Concluído',
    failed: 'Falhou',
  },
  itemStatus: {
    distribution: 'Redistribuição',
    adequate: 'Adequado',
    boost: 'Impulsionar',
  },
} as const;
